from SCons.Node.FS import find_file

env = Environment(CPPPATH = ["include"], LIBS=["boost_unit_test_framework-mt", "boost_program_options-mt", "boost_serialization-mt"])
env.Program("maxent", Glob("src/*.cpp"))

test_sources = Glob("test/*.cpp")
test_sources.extend(Glob("src/*.cpp"))
test_sources = filter(lambda f: f.name != "maxent.cpp", test_sources)
env.Program("tests", test_sources)
